// sharelib_chvapi.h: interface for the CHVAPI class.
//
//////////////////////////////////////////////////////////////////////

#ifndef DH_SHARE_LIB_CHVAPI_H__
#define DH_SHARE_LIB_CHVAPI_H__

//类型声明，用户自行定义CDHCameraObj.h的实现
#include "..\\CDHCameraObj.h"

/*
问题列表：
1 DHCAM_ADV_FEATURE_INQ_OFFSET有一些地址找不到
*/

// 获取ADV_FEATURE_INQ 查询寄存器地址
HVSTATUS DHCAM_ADV_FEATURE_INQ_OFFSET(HV_ADV_FEATURE_ID ID,DWORD &dwOffset);
// 获取ADV_FEATURE 控制寄存器地址
HVSTATUS DHCAM_ADV_FEATURE_OFFSET(HV_ADV_FEATURE_ID ID,DWORD &dwOffset);


class sharelib_hvapi
{
public:
    sharelib_hvapi(CCamera *pCamera):m_pCamera(pCamera){};
    ~sharelib_hvapi(){};

    HVSTATUS Control(
        const DWORD code,
        PVOID pInBuff,
        const DWORD dwInBuffSize,
        PVOID pOutBuff,
        const DWORD dwOutBuffSize,
        DWORD *pBytesReturned = NULL);

private:
    CCamera *m_pCamera;


// 定义CHVAPI::Control的参数列表，简化函数声明
#ifdef HVAPI_PARAM_LIST
#undef HVAPI_PARAM_LIST
#endif

#define HVAPI_PARAM_LIST  \
	void* pInBuff, \
	const DWORD dwInBuffSize, \
	void* pOutBuff, \
	const DWORD dwOutBuffSize, \
	DWORD *pBytesReturned = NULL

// 设置返回值
#define MAC_SET_RETURN_BYTES(pBytesReturned, Value)  \
	{\
	if((pBytesReturned)!=NULL) \
	*(DWORD*)(pBytesReturned)=(DWORD)(Value);\
	}


    //HVInter.h 接口, ORD_RawIO.cpp
    HVSTATUS Fun_ORD_READ_QUADLET(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_WRITE_QUADLET(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_READ_BLOCK(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_WRITE_BLOCK(HVAPI_PARAM_LIST);

    //HVDef.h 接口
    HVSTATUS Fun_ORD_INIT_CAMERA(HVAPI_PARAM_LIST);

    HVSTATUS Fun_ORD_QUERY_STRING_PRESENCE(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_QUERY_STRING_DESCRIPTOR(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_GET_STRING(HVAPI_PARAM_LIST);

    HVSTATUS Fun_ORD_QUERY_RESET_CAMERA_PRESENCE(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_RESET_CAMERA(HVAPI_PARAM_LIST);

    HVSTATUS Fun_ORD_QUERY_LAST_STATUS_PRESENCE(HVAPI_PARAM_LIST);

    HVSTATUS Fun_ORD_QUERY_VIDEO_FORMAT_PRESENCE(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_QUERY_VIDEO_MODE_PRESENCE(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_QUERY_FRAME_RATE_PRESENCE(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_GET_VIDEO_FORMAT_MODE_FRAME_RATE(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_SET_VIDEO_FORMAT_MODE_FRAME_RATE(HVAPI_PARAM_LIST);

    HVSTATUS Fun_ORD_QUERY_FMT7_MODE_DESCRIPTOR(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_GET_FMT7_MODE(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_SET_FMT7_MODE(HVAPI_PARAM_LIST);

    HVSTATUS Fun_ORD_QUERY_FEATURE_PRESENCE(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_QUERY_FEATURE_DESCRIPTOR(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_GET_FEATURE(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_SET_FEATURE(HVAPI_PARAM_LIST);

    HVSTATUS Fun_ORD_QUERY_BASIC_FUNC_PRESENCE(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_QUERY_BASIC_FUNC_DESCRIPTOR(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_GET_BASIC_FUNC(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_SET_BASIC_FUNC(HVAPI_PARAM_LIST);

    HVSTATUS Fun_ORD_QUERY_OPT_FUNC_PRESENCE(HVAPI_PARAM_LIST);

    HVSTATUS Fun_ORD_QUERY_PIO_OUTPUT_PORT_PRESENCE(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_QUERY_PIO_OUTPUT_PORT_DESCRIPTOR(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_GET_PIO_OUTPUT_PORT(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_SET_PIO_OUTPUT_PORT(HVAPI_PARAM_LIST);

    HVSTATUS Fun_ORD_QUERY_SIO_DESCRIPTOR(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_GET_SIO(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_SET_SIO(HVAPI_PARAM_LIST);

    HVSTATUS Fun_ORD_QUERY_STROBE_PRESENCE(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_QUERY_STROBE_DESCRIPTOR(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_GET_STROBE(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_SET_STROBE(HVAPI_PARAM_LIST);

    // ORD_SNAP.cpp
    HVSTATUS Fun_ORD_OPEN_SNAP(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_START_SNAP(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_STOP_SNAP(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_CLOSE_SNAP(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_SNAP_SHOT(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_TRIGGER_SHOT(HVAPI_PARAM_LIST);

    HVSTATUS Fun_ORD_SNAP_SHOT_EX(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_REGISTER_CALLBACK(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_DEREGISTER_CALLBACK(HVAPI_PARAM_LIST);

    HVSTATUS Fun_ORD_QUERY_ADV_FEATURE_PRESENCE(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_QUERY_ADV_FEATURE_DESCRIPTOR(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_GET_ADV_FEATURE(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_SET_ADV_FEATURE(HVAPI_PARAM_LIST);

    HVSTATUS Fun_ORD_QUERY_ADV_BASIC_FUNC_PRESENCE(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_GET_ADV_BASIC_FUNC(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_SET_ADV_BASIC_FUNC(HVAPI_PARAM_LIST);

    HVSTATUS Fun_ORD_QUERY_ADV_OPT_FUNC_PRESENCE(HVAPI_PARAM_LIST);

    HVSTATUS Fun_ORD_QUERY_ADV_LUT_DESCRIPTOR(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_GET_ADV_LUT(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_SET_ADV_LUT(HVAPI_PARAM_LIST);

    HVSTATUS Fun_ORD_QUERY_ADV_USER_CUSTOM_DESCRIPTOR(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_GET_ADV_USER_CUSTOM(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_SET_ADV_USER_CUSTOM(HVAPI_PARAM_LIST);


    HVSTATUS Fun_ORD_QUERY_ADV_USER_ENCRYPT_ZONE_PRESENCE(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_QUERY_ADV_USER_ENCRYPT_ZONE_DESCRIPTOR(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_GET_ADV_USER_ENCRYPT_ZONE(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_SET_ADV_USER_ENCRYPT_ZONE(HVAPI_PARAM_LIST);


    HVSTATUS Fun_ORD_QUERY_NET_FUNC_PRESENCE(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_QUERY_NET_FUNC_DESCRIPTOR(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_GET_NET_FUNC(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_SET_NET_FUNC(HVAPI_PARAM_LIST);

    HVSTATUS Fun_ORD_QUERY_IMAGE_INFO_PRESENCE(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_QUERY_IMAGE_INFO_DESCRIPTOR(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_GET_IMAGE_INFO(HVAPI_PARAM_LIST);


    HVSTATUS Fun_ORD_QUERY_AUTO_FUNC_PRESENCE(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_QUERY_AUTO_FUNC_DESCRIPTOR(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_GET_AUTO_FUNC(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_SET_AUTO_FUNC(HVAPI_PARAM_LIST);

    ///  add by xupx 2009.05.27
    HVSTATUS Fun_ORD_QUERY_OSD_FUNC_PRESENCE(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_QUERY_OSD_FUNC_DESCRIPTOR(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_GET_OSD_FUNC(HVAPI_PARAM_LIST);
    HVSTATUS Fun_ORD_SET_OSD_FUNC(HVAPI_PARAM_LIST);

private:
    HVSTATUS ReadQuadlet(DWORD dwOffset, DWORD *pValue);
    HVSTATUS WriteQuadlet(DWORD dwOffset, DWORD dwValue);
    HVSTATUS ReadBlock(DWORD dwOffset, PBYTE pOutBuff, DWORD outBufSize);
    HVSTATUS WriteBlock(DWORD dwOffset, PBYTE pInBuff, DWORD outInfSize);
};

#undef HVAPI_PARAM_LIST


#endif // !defined(DH_SHARE_LIB_CHVAPI_H__)
